### ISSUE TITLE
Uncaught exception 'Http\Client\Exception\RequestException' with message 'No URL set!'

### ISSUE THREAD

**Issue by wallter** [mailerlite/mailerlite-api-v2-php-sdk#9]
### Steps

1. `$ composer require mailerlite/mailerlite-api-v2-php-sdk`
2. Script: _(using [GUMP](https://github.com/Wixel/GUMP) for sanitization)_

```PHP
require_once ('../vendor/autoload.php'); // composer autoloader
require_once ('../src/config.php');      // @param Array $config

// Initalize GUMP and MailerLite
$gump         = new GUMP();
$mailer       = new \MailerLiteApi\MailerLite($config['mailerlite']['api_key']);
$mailerGroups = $mailer->groups();

// Sanatize input and merge with defaults
$_REQUEST = $gump->xss_clean($gump->sanitize($_REQUEST));
$input    = array_merge($config['mailerlite']['defaults'], $_REQUEST);

// Set Validation and Filtering rules
$gump->validation_rules($config['mailerlite']['validation_rules']);
$gump->filter_rules($config['mailerlite']['filter_rules']);

// Run validation and filtering
$subscriberData = $gump->run($input);

// return errors if nessassary
if (!$subscriberData) {
  die(json_encode([
    'status'  => false,
    'data'    => $grump->get_errors_array(),
    'message' => $gump->get_readable_errors(true)
  ]));
}

// Fire Mailerlite addSubscriber() request via
//   Official mailerlite-api-v2-php-sdk SDK
//
// This causes a Fatal error:
//   Uncaught exception 'Http\Client\Exception\RequestException' with message 'No URL set!'
$response = $mailerGroups->addSubscriber(
  $config['mailerlite']['group_id'],
  $subscriberData
);

// Fatal error: Uncaught exception 'Http\Client\Exception\RequestException' with message 'No URL set!' in vendor/php-http/curl-client/src/Client.php:136
// Stack trace:
// #0 vendor/mailerlite/mailerlite-api-v2-php-sdk/src/Common/RestClient.php(97): Http\Client\Curl\Client->sendRequest(Object(GuzzleHttp\Psr7\Request))
// #1 vendor/mailerlite/mailerlite-api-v2-php-sdk/src/Common/RestClient.php(56): MailerLiteApi\Common\RestClient->send('POST', 'groups/6256321/...', Array)
// #2 vendor/mailerlite/mailerlite-api-v2-php-sdk/src/Api/Groups.php(45): MailerLiteApi\Common\RestClient->post('groups/6256321/...', Array)
// #3 public/mailerlite_add_subscriber.php(36): MailerLiteApi\Api\Groups- in vendor/php-http/curl-client/src/Client.php on line 136

// [Code Unreachable due to Fatal error above]
// End the script by echoing out JSON to let the caller know the status and any errors
die(json_encode([
  'status'  => (!!$response),
  'data'    => $grump->get_errors_array(),
  'message' => "Successfully subscribed {$input['name']} to mailerlite group '{$config['mailerlite']['group_id']}'"
]));
```
### Error Message
> Fatal error: Uncaught exception 'Http\Client\Exception\RequestException' with message 'No URL set!' in vendor/php-http/curl-client/src/Client.php:136
Stack trace:
> #0 vendor/mailerlite/mailerlite-api-v2-php-sdk/src/Common/RestClient.php(97): Http\Client\Curl\Client->sendRequest(Object(GuzzleHttp\Psr7\Request))
> #1 vendor/mailerlite/mailerlite-api-v2-php-sdk/src/Common/RestClient.php(56): MailerLiteApi\Common\RestClient->send('POST', 'groups/6256321/...', Array)
> #2 vendor/mailerlite/mailerlite-api-v2-php-sdk/src/Api/Groups.php(45): MailerLiteApi\Common\RestClient->post('groups/6256321/...', Array)
> #3 public/mailerlite_add_subscriber.php(36): MailerLiteApi\Api\Groups- in vendor/php-http/curl-client/src/Client.php on line 136

**Comment by justinasposiunas** [comment]
Hey, sorry for the delay. Can you tell which PHP version you are using?

**Comment by wallter** [comment]
Google Cloud PHP 5.5
